apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: someapp-replicaset
  labels:
    app: someapp
    type: front-end
spec:
  template:
    metadata:
      name: someapp-pod
      labels:
        app: someapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: someapp